Добавление диаграммы состояний приложения
Winterpuma/bmstu_team-development pull request #28
Opened 2021-03-29 15:20 UTC by UselessSaint

Добавление диаграммы состояний приложения (closes #3).
Я случайно миссклинул на enter когда создавал тот реквест >_>

2021-03-29 18:00 UTC, Winterpuma commented
Заполни пж правильно правую колонку в соответствии с issue

2021-03-29 18:03 UTC, Winterpuma requested changes
Нужно правильно дооформлять мердж. По диаграмме норм.

2021-03-29 18:06 UTC, UselessSaint commented
Поправил инфу о реквесте

2021-03-29 18:10 UTC, Winterpuma approved these changes

2021-03-30 19:51 UTC, anastasialavrova reviewed
Ок

2021-03-30 19:58 UTC, anastasialavrova approved these changes
Ок

2021-03-30 23:45 UTC, merged