Добавил базовую реализацию класса Creature #14
Winterpuma/bmstu_team-development pull request #32
Opened 2021-04-05 01:16 UTC by UselessSaint

Я пока что не добавил возможность прыжка, так как с этим есть проблемы. Добавлю скоро. Пока что есть базовое передвижение и все такое. В теории должно хватить для начала работы над NPC. Алсо хз нужно или коммитить packages-lock.json, оверфлоу говорит что да, поэтому воть. 
Issue не закрываю, бтв.

А еще я не помню как сделать крутой авто-медж, сорян.

2021-04-05 08:50 UTC, Winterpuma commented
Крутой авто-мердж тут

![image](https://user-images.githubusercontent.com/32524078/113556440-271ac200-9605-11eb-8c3c-adde84e792d4.png)

2021-04-05 09:04 UTC, UselessSaint commented
![image](https://user-images.githubusercontent.com/32227002/113557631-fe93c780-9606-11eb-883c-d6d1466357ef.png)
нус у меня сейчас вот так вот

2021-04-05 09:12 UTC, Winterpuma requested changes
Мои комментарии самостоятельно не закрывать. Можно указать что исправлено. 

Номер ишью должен быть не в названии пул реквета а в описании со спец словом (посмотри прошлые), так, чтобы в linked issues появилась ссылка. Если ишью закрывать не хочешь, то просто ручками добавить в linked issues

2021-04-05 09:12 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +*/
В девелопе не должно быть закомментированного кода. Когда коммитишь, в гитхаб десктопе можно выделить какие изменения(построчно) не коммитить

2021-04-05 09:12 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    private bool _isGrounded;
Цитата из нашего кодстайла:
Class member ordering:
* Group class members in the following order:
   * Nested classes, enums, delegates and events.
   * Static, const and readonly fields.
   * Fields and properties.
   * Constructors and finalizers.
   * Methods.
* Within each group, elements should be in the following order:
Public.
Internal.
Protected internal.
Protected.
Private.

2021-04-05 09:12 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +        transform.position += (_movementDirection*_movementSpeed*Time.fixedDeltaTime);
Где пробелы, зачем скобки? Ниже соответственно

2021-04-05 09:12 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    }
Это точно нельзя более компактно написать?

2021-04-05 09:13 UTC, Winterpuma commented
> ![image](https://user-images.githubusercontent.com/32227002/113557631-fe93c780-9606-11eb-883c-d6d1466357ef.png)
> нус у меня сейчас вот так вот

Ну да) Кнопку видишь большую?))))))))))))))))))))))))

2021-04-05 09:20 UTC, UselessSaint commented
А о, его прожать надо

2021-04-05 09:21 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    private bool _isGrounded;
https://google.github.io/styleguide/csharp-style.html

2021-04-05 09:22 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    }
Тебе жалко строки кода?

Я могу убрать скобки, но шо там по код стайлу в такой ситуации?
Если после выражения только одна строка то нужно без скобок?

2021-04-05 09:37 UTC, UselessSaint commented
Залинковал issue

2021-04-05 09:55 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +*/
Убрал

2021-04-05 09:55 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    private bool _isGrounded;
Поправил

2021-04-05 09:55 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +        transform.position += (_movementDirection*_movementSpeed*Time.fixedDeltaTime);
Поправил

2021-04-05 09:56 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +    }
И ето поправил

2021-04-05 11:20 UTC, UselessSaint commented
Черт, я забыл кое-то что убрать, не закрывайте issue
Хочу еще кое-что потестить

2021-04-05 13:34 UTC, Winterpuma submitted a review, later dismissed

2021-04-06 23:53 UTC, anastasialavrova submitted a review, later dismissed
Небольшое замечание: лучше между комментарием и методом не оставлять пустой строки
В остальном все хорошо

2021-04-07 09:45 UTC, Winterpuma commented
> Небольшое замечание: лучше между комментарием и методом не оставлять пустой строки
> В остальном все хорошо

Почему это небольшое замечание?)) Я бы требовала таких комментариев ))
![image](https://user-images.githubusercontent.com/32524078/113845657-6af4ff00-979e-11eb-9854-3a861d4e5cd3.png)

Кстати у меня в студии добавился такой прикол после установки пакета c#.  

Для vs code: https://marketplace.visualstudio.com/items?itemName=k--kato.docomment

**Использование: прямо над методом пишем /// и жмем enter**

2021-04-08 14:43 UTC, Winterpuma requested changes

2021-04-08 14:43 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +        _groundCheckRayLenght = _collider.size.y / 2 * transform.localScale.y + 0.05f;
Что за число 0.05?

2021-04-08 14:43 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            if(Mathf.Sign(_movementDirection.x) != Mathf.Sign(_rigidbody.velocity.x) || _movementDirection.x == 0.0f)
почему 0.0.. Исправь пж все магические числа, которые ниже тоже. Их можно вынести в этот или отдельный класс как константы. Мы с тобой это уже обсуждали

2021-04-08 14:55 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            if(Mathf.Sign(_movementDirection.x) != Mathf.Sign(_rigidbody.velocity.x) || _movementDirection.x == 0.0f)
Это не магическое число. Я просто смотрю куда направлена х составляющая вектора и если она равна 0 то делаю то что делаю. Если нужно я могу создать переменную _zero = 0.0f.

2021-04-08 14:57 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            if(Mathf.Sign(_movementDirection.x) != Mathf.Sign(_rigidbody.velocity.x) || _movementDirection.x == 0.0f)
(если х составляющая равна 0, то я предполагаю что х составляющая никуда не направлена)

2021-04-08 16:02 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            _rigidbody.drag = _linearDrag * 0.1f;
Ну а вот это не магический коэффициент??

2021-04-08 16:06 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            if(Mathf.Sign(_movementDirection.x) != Mathf.Sign(_rigidbody.velocity.x) || _movementDirection.x == 0.0f)
Возможно нули и не стоит выносить, но там есть и другие коэфы.

2021-04-08 16:06 UTC, Winterpuma commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            if(Mathf.Sign(_movementDirection.x) != Mathf.Sign(_rigidbody.velocity.x) || _movementDirection.x == 0.0f)
Путь @anastasialavrova  откоментит

2021-04-08 16:09 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +            _rigidbody.drag = _linearDrag * 0.1f;
Это я уже поправил давно, ждал ответа по тому вопросу чтоб закомитить все и сразу

2021-04-08 16:09 UTC, UselessSaint commented on SimpleStory/Assets/Scripts/Creatures/Creature.cs
> +        _groundCheckRayLenght = _collider.size.y / 2 * transform.localScale.y + 0.05f;
Это тоже поправил

2021-04-08 16:42 UTC, Winterpuma approved these changes

2021-04-09 08:14 UTC, anastasialavrova approved these changes

2021-04-09 14:32 UTC, merged